from django.urls import include, path
from . import views
from django.contrib import admin
from .views import upload_blood, succ

urlpatterns = [
    path('',views.index,name='index'),
    path('index.html/',views.index,name='index'),
    path('index.html/index.html',views.index,name='index'),
    path('index.html/saveform',views.saveform,name='saveform'),
    path('index.html/contact.html',views.contact,name='contact'),
    path('index.html/login.html',views.loginpage,name='loginpage'),
    path('index.html/search',views.search_blood_banks,name='search_blood_banks'),
    path('index.html/track',views.track_donation_status,name='track_donation_status'),
    path('contact.html/',views.contact,name='contact'),
    path('contact.html/saveform',views.saveform,name='saveform'),
    path('contact.html/index.html',views.index,name='index'),
    path('contact.html/login.html',views.loginpage,name='loginpage'),
    path('contact.html/track',views.track_donation_status,name='track_donation_status'),
    path('contact.html/search',views.search_blood_banks,name='search_blood_banks'),
    path('search/', views.search_blood_banks, name='search_blood_banks'),
    path('search/index.html', views.index, name='index'),
    path('search/contact.html', views.contact, name='contact'),
    path('search/login.html',views.loginpage,name='loginpage'),
    path('search/saveform', views.saveform, name='saveform'),
    path('search/track',views.track_donation_status,name='track_donation_status'),
    path('saveform/',views.saveform, name='saveform'),
    path('success/', views.success, name='success'),  # Add this line
    path('saveform/index.html',views.index,name='index'),
    path('saveform/login.html',views.loginpage,name='loginpage'),
    path('saveform/contact.html',views.contact,name='contact'),
    path('saveform/search',views.search_blood_banks,name='search_blood_banks'),
    path('saveform/track',views.track_donation_status,name='track_donation_status'),
    path('login.html/', views.loginpage, name='loginpage'),
    path('login.html/login.html', views.loginpage, name='loginpage'),
    path('login.html/index.html',views.index,name='index'),
    path('login.html/saveform',views.saveform,name='saveform'),
    path('login.html/contact.html',views.contact,name='contact'),
    path('login.html/search',views.search_blood_banks,name='search_blood_banks'),
    path('login.html/track',views.track_donation_status,name='track_donation_status'),
    path('success/index.html',views.index,name='index'),
    path('success/saveform',views.saveform,name='saveform'),
    path('success/login.html', views.loginpage, name='loginpage'),
    path('success/contact.html',views.contact,name='contact'),
    path('success/track',views.track_donation_status,name='track_donation_status'),
    path('track/', views.track_donation_status, name='track_donation_status'),
    path('track/index.html',views.index,name='index'),
    path('track/login.html', views.loginpage, name='loginpage'),
    path('track/contact.html',views.contact,name='contact'),
    path('track/saveform',views.saveform,name='saveform'),
    path('track/search',views.search_blood_banks,name='search_blood_banks'),
    path('upload/', views.upload_blood, name='upload_blood'),
    path('upload/succ',views.succ,name='succ'),
    path('succ/', views.succ, name='succ'),
    path('succ/index.html', views.index, name='index'),

]
